/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.fischerabruzese

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun runTestSol() {
        val prob =
            PythonProblem(
                description =
"""
Return the sum of the first 101 fib numbers. The first 3 fib numbers are 0 1 1.
""",
                starterCode =
"""
def solution():
	return 0
""",
                solution = "500",
            )

        val testSolution =
"""
def solution():
	return 500
"""
        println(App().runSandboxedPython(testSolution))
    }
}
